# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoPaterno', models.CharField(max_length=30)),
                ('apellidoMaterno', models.CharField(max_length=30)),
                ('carrera', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('secso', models.CharField(max_length=2)),
            ],
        ),
    ]
